spring:
  application:
    name: pokedex
  cloud:
    openfeign:
      okhttp:
        enabled: true
      client:
        config:
          poke-api-client:
            url: https://pokeapi.co/api/v2
